### ISSUE TITLE
[Submission] Xiaomi Mi A1 Dual Speaker Mod

### ISSUE THREAD

**Issue by WhatzIt2Ya** [Magisk-Modules-Repo/submission#292]
https://github.com/WhatzIt2Ya/tissotstereomod/tree/master

**Comment by yochananmarqos** [comment]
The `REPLACE` function is not for files.

**Comment by WhatzIt2Ya** [comment]
Really? I just followed a tutorial. :D

**Comment by yochananmarqos** [comment]
What tutorial was that?

**Comment by WhatzIt2Ya** [comment]
Dante63's video https://www.youtube.com/watch?v=Su9Af-jrJWQ

**Comment by yochananmarqos** [comment]
He might be good at sound mods, but Magisk modules? Not so much.

**Comment by WhatzIt2Ya** [comment]
So is my module clear? Anything I have to edit? I'm sorry, it's my first magisk module.

**Comment by yochananmarqos** [comment]
Since it's only for certain devices, you'll need to add a device check.

**Comment by WhatzIt2Ya** [comment]
I've updated it. I couldn't find any guides or modules that have device check, even the device specific ones. I've only found one module that has it, Enable MIAI for Mi 6X. If I can't install my module to my phone, I'm going to have to remove it, as I have no clue how to add it.

**Comment by WhatzIt2Ya** [comment]
I've removed the "device check" from my module because
a) I couldn't install the module
b) I think it's not necessary as most modules from magisk-repo don't have device check
c) I couldn't find anything about adding a device check online
I hope you understand my decision. Unless, you could help me add it.

**Comment by Didgeridoohan** [comment]
Just because modules already in the repo doesn't have device checks doesn't mean that we moderators can't try to keep some order with the modules we allow in now...

It's a simple "if this then that" check for a prop value. Try to get it working.

**Comment by Stallix** [comment]
https://github.com/Magisk-Modules-Repo/MiA2Camera/commit/42ece73c467b40bca2b1509631d3e32ccfb5ecf0

**Comment by WhatzIt2Ya** [comment]
@yochananmarqos Mod Complete! Thanks to joeyhaub for helping me. Mod works okay now, added device check.

**Comment by Didgeridoohan** [comment]
Nope...

You have not been paying any attention to the instructions on how to make a module and submit it to the repo. Do NOT add anything to update-binary, since it will be replaced during installation. Only use install.sh for any custom installation logic.

If you're going to submit a module, please do your homework first...

**Comment by WhatzIt2Ya** [comment]
My apologies. The fault is all mine. Like I've said, it's my first module. All fixed now. Device check added to install script. I had to reupload some files as they were screwed up. (Probably why I couldn't install them)

**Comment by Didgeridoohan** [comment]
You still have the file in the REPLACE variable. That's for directories, not files.

And (as stated in the instructions) don't use `exit`, but the Magisk specific command `abort`.

**Comment by WhatzIt2Ya** [comment]
Thanks. Redone! #3
